apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: knative-webhook-sensor
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
    # sensor controller will use this label to match with it's own version
    # do not remove
    argo-events-sensor-version: v0.11
spec:
  template:
    metadata:
      hello: world
    spec:
      serviceAccountName: argo-events-sa
  knativeservice:
    metadata:
      name: "knative-sensor"
    template:
      spec:
        containers:
        - image: "kpavel/sensor:v0.11"
          name: "sensor"
  dependencies:
    - name: "knative-webhook-gateway:example"
  eventProtocol:
    type: "HTTP"
    http:
      port: "8080"
  triggers:
    - template:
        name: webhook-workflow-trigger
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        source:
          inline: |
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: webhook-
            spec:
              entrypoint: whalesay
              arguments:
                parameters:
                - name: message
                  # this is the value that should be overridden
                  value: hello world
              templates:
              - name: whalesay
                inputs:
                  parameters:
                  - name: message
                container:
                  image: docker/whalesay:latest
                  command: [cowsay]
                  args: ["{{inputs.parameters.message}}"]
      resourceParameters:
        - src:
            event: "knative-webhook-gateway:example"
          dest: spec.arguments.parameters.0.value
